### ISSUE TITLE
This should be a gist.

### ISSUE THREAD

**Issue by daveloyall** [sekritskwurl/crypto_fun#1]
https://gist.github.com/

You can even name the file.

**Comment by daveloyall** [comment]
Meanwhile, the Debian source for the gpgv package lives at git://anonscm.debian.org/pkg-gnupg/gnupg.git .

The upstream sources are at git://git.gnupg.org/gnupg.git .

Any reason for targeting 1.4.x instead of 2.0.x?

**Comment by sekritskwurl** [comment]
I did not know that comments were a thing. That is neat. 

Why a gist? Not enough code for a proper github page? lol

**Comment by daveloyall** [comment]
Basically yeah. :)

**Comment by daveloyall** [comment]
So, git can emit patch files.  I'm not sure how to do it.

**Comment by sekritskwurl** [comment]
I can handle that shame. I'm pretty proud i did the github thing from the command line. I take so much from github. probably time to give a little back. ;)

**Comment by daveloyall** [comment]
One advantage to using SCM tool features for this kind of thing is that you can more easily see what changed.  I took your script and ran it against a copy of the source that I made quick for this purpose... So it's just as if I'd hand-edited the files--but I did run your script.  You can easily see the results here: https://github.com/daveloyall/gnupg/compare/for-sekrit

**Comment by daveloyall** [comment]
My favorites: 

* https://github.com/daveloyall/gnupg/compare/for-sekrit#diff-fb2ad780752a6de83fbc241905020fd5L20 
* https://github.com/daveloyall/gnupg/compare/for-sekrit#diff-807ba419efd30313e04a4cc694b6feb7L2365
* https://github.com/daveloyall/gnupg/compare/for-sekrit#diff-dbcbf8653afd6c733a210bfa3e1be559L126

;)

**Comment by sekritskwurl** [comment]
so basically, do not use, for anything. 

You should see the actual RSA implementation I have, it's a little cleaner, but takes forever to generate keys.
